name: Pages
on: [push]
inputs:
  - name: documentation_path
    description: Path to the documentation directory
    required: true
    default: docs
  - name: install_requirements
    description: Install requirements before building the documentation
    required: true
    default: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Build and Commit
      uses: sphinx-notes/pages@master
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages